//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarpoolLog
    {
        public string username { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<short> driver { get; set; }
        public Nullable<short> passenger { get; set; }
    
        public virtual User User { get; set; }
    }
}
