//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total
    {
        public string username { get; set; }
        public Nullable<int> passenger_total { get; set; }
        public Nullable<int> driver_total { get; set; }
        public Nullable<int> carpool_total { get; set; }
    }
}
